### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by Kishiko** [devscast/covid19-backend#1]
We need FAQ items about the Covid-19 disease. While [WHO FAQ](https://www.who.int/news-room/q-a-detail/q-a-coronaviruses) are on top of our focus, a tailored FAQ items related to DRC environment and ecosystem is a must.

So, here are FAQ items provided by WHO (https://www.who.int/news-room/q-a-detail/q-a-coronaviruses). Above that, comment that issue to add DRC-related FAQ items for those to be added in the app.

**Comment by bernard-ng** [comment]
@Kishiko It's a good idea, the big problem we have at the moment is the lack of a translator for the national languages.

otherwise you can already propose the questions and answers we will add them without any problem.

**Comment by lucienmakutano** [comment]
getting translator might not be a big problem, the problem is to know what to translate because
we can still ask for help from RTNC's journalists. I am sure they might help after all they defuse news in the four different national languages and COVID-19 is a problem that touches all of us.

**Comment by bernard-ng** [comment]
@Kishiko  is something missing here ?

What is a coronavirus?
What is COVID-19?
What are the symptoms of COVID-19?
How does COVID-19 spread?
What can I do to protect myself and prevent the spread of disease?
How likely am I to catch COVID-19?
Should I worry about COVID-19?
Who is at risk of developing severe illness?
Are antibiotics effective in preventing or treating the COVID-19?
Are there any medicines or therapies that can prevent or cure COVID-19?
Is there a vaccine, drug or treatment for COVID-19?
Is COVID-19 the same as SARS?
Should I wear a mask to protect myself?
How to put on, use, take off and dispose of a mask?
How long is the incubation period for COVID-19?
Can humans become infected with the COVID-19 from an animal source?
Can I catch COVID-19 from my pet?
How long does the virus survive on surfaces?
Is it safe to receive a package from any area where COVID-19 has been reported?
Is there anything I should not do?

**Comment by Arcenebeya** [comment]
@bernard-ng @tadomikikuto-bit  I can assist with the translation in Tshiluba, French and Lingala. If possible, I would like to be proof read by another person. Thanks!

**Comment by lucienmakutano** [comment]
@bernard-ng what do you say??
I can assist @Arcenebeya on the French part.

**Comment by bernard-ng** [comment]
@Kishiko is working on, we will ping you once he's finished so that you can start contributing and correcting possible mistakes...

**Comment by Arcenebeya** [comment]
@bernard-ng @Kishiko That's great!

**Comment by bernard-ng** [comment]
@Kishiko still waiting for you :)
