### ISSUE TITLE
Update news posts from authority sources

### ISSUE THREAD

**Issue by Kishiko** [devscast/covid19-backend#13]
The [homepage ](https://covid-19info.cd/dashboard) displays news related to the Covid-19 disease. Which is fine for spreading additional news beyond the cases reported. However, that news is outdated. See screenshot below.

![screenshot-covid-19info cd-2020 03 26-13_24_14](https://user-images.githubusercontent.com/29162210/77642933-2584db80-6f67-11ea-905a-6c06ce947b78.png)

To make it better and updated daily, it would be better to post news from authority sources such as:

1. The [DRC Health Department](https://twitter.com/MinSanteRDC) (Twitter account)
2. The [Institut National de Recherche Biomédicale (INRB)](https://twitter.com/inrb_kinshasa) (Twitter account)
3. The [Wolrd Head Organization in DRC](https://twitter.com/OMSRDCONGO) (Twitter account)

**Comment by bernard-ng** [comment]
our administration is working on that, anyway thanks for reporting this issue
