### ISSUE TITLE
Paginate countries' page

### ISSUE THREAD

**Issue by oesukam** [devscast/covid19-backend#7]
**Page**: [https://covid-19info.cd/countries](https://covid-19info.cd/countries)

**Problem:**
- Listing all countries doesn't give a good user experience even if there is a search bar

**Recommendation:**
- It will be better to include pagination and filters per continent and regions if possible
- Also having a possibility to sort countries by differents information such as the most affected, having active cases, recovered and so on

**Comment by bernard-ng** [comment]
@oesukam we use the jhu api for countries, you can reopen this issue, on the repository https://github.com/devscast/covid19-client
 it's the frontend that has to take care of this.
